import tkinter as tk
from tkinter import *
import random
import string
import pyperclip


# the generator function adds random characters to the variable password
def generator():
    password = ""

    for x in range(0, 4):
        password = random.choice(string.ascii_lowercase) + random.choice(string.ascii_uppercase) + \
                 random.choice(string.digits) + random.choice(string.punctuation)
    for y in range(pass_len.get() - 4):
        password = password + random.choice(string.ascii_lowercase + string.ascii_uppercase +
                                            string.digits + string.punctuation)
    pass_str.set(password)


# copy password function allows the GUI to copy the password generated by the generator function
def copy_password():
    pyperclip.copy(pass_str.get())


# Create the Window, set size, set title
root = Tk()
root.geometry("250x250")
root.title("Password Generator")

# Create the Canvas and attach it to the window
d = tk.Canvas(root, bg="#809fff")

Label(d, text="Password Length", font="Times 18", bg="#809fff").pack(pady=5)
pass_len = IntVar()
Spinbox(d, from_=8, to_=24, textvariable=pass_len, width=25).pack(pady=5)
pass_str = StringVar()
Button(d, text="Generate", command=generator, bg="#0040ff", fg="#ccd9ff").pack(pady=5)
Entry(d, textvariable=pass_str).pack()
Button(d, text="Copy Password", command=copy_password, bg="#0040ff", fg="#ccd9ff").pack(pady=5)
Button(d, text="Exit", command=root.destroy, bg="#800000", fg="#ffb3b3").pack(pady=5)
Label(d, text="Password Generator created by Philip Ginter").pack(side=BOTTOM)
# declare Variables


# Execute the user interface
d.pack(fill=BOTH, expand=True)
root.mainloop()
